version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "portfolio"
    volumes:
      - postgres:/data/db/postgres

volumes:
  postgres:
