"""Add group table.

Revision ID: 055bb413e8ce
Revises: d2052311801f
Create Date: 2023-02-19 13:19:56.103818

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "055bb413e8ce"
down_revision = "d2052311801f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="portfolio",
    )
    op.add_column("image", sa.Column("group_id", sa.Integer(), nullable=True), schema="portfolio")
    op.create_foreign_key(
        None,
        "image",
        "group",
        ["group_id"],
        ["id"],
        source_schema="portfolio",
        referent_schema="portfolio",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "image", schema="portfolio", type_="foreignkey")
    op.drop_column("image", "group_id", schema="portfolio")
    op.drop_table("group", schema="portfolio")
    # ### end Alembic commands ###
