"""Add profile_picture_path column to the user table.

Revision ID: 3be74c05c2e0
Revises: 800822ad54e2
Create Date: 2023-02-13 22:46:46.724444

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3be74c05c2e0"
down_revision = "800822ad54e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("profile_picture_path", sa.String(), nullable=True),
        schema="portfolio",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "profile_picture_path", schema="portfolio")
    # ### end Alembic commands ###
