"""Add portfolio.image table.

Revision ID: 5e308f9c6e75
Revises: 3a6a7fb6aaf6
Create Date: 2022-12-07 19:29:48.344875

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5e308f9c6e75"
down_revision = "3a6a7fb6aaf6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("blur_hash", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("full_s3_url", sa.String(), nullable=False),
        sa.Column("thumbnail_s3_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="portfolio",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("image", schema="portfolio")
    # ### end Alembic commands ###
