"""Update image table to contain nullable fields.

Revision ID: ad221fafd493
Revises: 1221b6e4dda5
Create Date: 2022-12-28 13:08:27.299420

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ad221fafd493"
down_revision = "1221b6e4dda5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "image",
        "description",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="portfolio",
    )
    op.alter_column("image", "city", existing_type=sa.VARCHAR(), nullable=True, schema="portfolio")
    op.alter_column(
        "image",
        "country",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="portfolio",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "image",
        "country",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="portfolio",
    )
    op.alter_column("image", "city", existing_type=sa.VARCHAR(), nullable=False, schema="portfolio")
    op.alter_column(
        "image",
        "description",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="portfolio",
    )
    # ### end Alembic commands ###
